ansible_network_os: eos
ansible_connection: httpapi
ansible_user: admin
ansible_password: admin
ansible_become: true
ansible_become_method: enable
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_python_interpreter: $(which python3)
